[project]
name = "USF_Lung_Cancer"
version = "0.1.0"
authors = ["Ethan Littlestone <ethanlittlestone@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64"]

[dependencies]
python = "3.11.*"
scanpy = ">=1.11.2,<2"
anndata = ">=0.11.4,<0.12"
pandas = ">=2.3.1,<3"
numpy = ">=2.2.6,<3"
matplotlib = ">=3.10.3,<4"
seaborn = "*"
jupyterlab = "*"
pixi = "*"
scipy = ">=1.16.0,<2"
pyreadr = ">=0.5.3,<0.6"
tqdm = ">=4.67.1,<5"
scvi-tools = ">=1.3.2,<2"
lightning = ">=2.5.2,<3"
pytorch = ">=2.7.1,<3"
r-base = ">=4.5.1,<4.6"
gfortran = ">=13.4.0,<13.5"
clang = ">=20.1.8,<21"
bat = ">=0.25.0,<0.26"

[tasks]
